In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('C:\\Users\\DELL\\Desktop\\Navya\\My Resume projects\\AI project\\7817_1.csv')
df.head()

id       asins   brand                  categories  \
0  AVpe7AsMilAPnD_xQ78G  B00QJDU3KY  Amazon  Amazon Devices,mazon.co.uk   
1  AVpe7AsMilAPnD_xQ78G  B00QJDU3KY  Amazon  Amazon Devices,mazon.co.uk   
2  AVpe7AsMilAPnD_xQ78G  B00QJDU3KY  Amazon  Amazon Devices,mazon.co.uk   
3  AVpe7AsMilAPnD_xQ78G  B00QJDU3KY  Amazon  Amazon Devices,mazon.co.uk   
4  AVpe7AsMilAPnD_xQ78G  B00QJDU3KY  Amazon  Amazon Devices,mazon.co.uk   

  colors             dateAdded           dateUpdated  \
0    NaN  2016-03-08T20:21:53Z  2017-07-18T23:52:58Z   
1    NaN  2016-03-08T20:21:53Z  2017-07-18T23:52:58Z   
2    NaN  2016-03-08T20:21:53Z  2017-07-18T23:52:58Z   
3    NaN  2016-03-08T20:21:53Z  2017-07-18T23:52:58Z   
4    NaN  2016-03-08T20:21:53Z  2017-07-18T23:52:58Z   

                  dimension  ean                         keys  ...  \
0  169 mm x 117 mm x 9.1 mm  NaN  kindlepaperwhite/b00qjdu3ky  ...   
1  169 mm x 117 mm x 9.1 mm  NaN  kindlepaperwhite/b00qjdu3ky  ...   
2  169 mm x 117 mm x 9.1 mm  NaN  kindlepaperwhite/b00qjdu3ky  ...   
3  169 mm x 117 mm x 9.1 mm  NaN  kindlepaperwhite/b00qjdu3ky  ...   
4  169 mm x 117 mm x 9.1 mm  NaN  kindlepaperwhite/b00qjdu3ky  ...   

  reviews.rating                                 reviews.sourceURLs  \
0            5.0  https://www.amazon.com/Kindle-Paperwhite-High-...   
1            5.0  https://www.amazon.com/Kindle-Paperwhite-High-...   
2            4.0  https://www.amazon.com/Kindle-Paperwhite-High-...   
3            5.0  https://www.amazon.com/Kindle-Paperwhite-High-...   
4            5.0  https://www.amazon.com/Kindle-Paperwhite-High-...   

                                        reviews.text  \
0  I initially had trouble deciding between the p...   
1  Allow me to preface this with a little history...   
2  I am enjoying it so far. Great for reading. Ha...   
3  I bought one of the first Paperwhites and have...   
4  I have to say upfront - I don't like coroporat...   

                                reviews.title reviews.userCity  \
0              Paperwhite voyage, no regrets!              NaN   
1           One Simply Could Not Ask For More              NaN   
2  Great for those that just want an e-reader              NaN   
3                    Love / Hate relationship              NaN   
4                                   I LOVE IT              NaN   

  reviews.userProvince    reviews.username  sizes upc     weight  
0                  NaN          Cristina M    NaN NaN  205 grams  
1                  NaN               Ricky    NaN NaN  205 grams  
2                  NaN       Tedd Gardiner    NaN NaN  205 grams  
3                  NaN              Dougal    NaN NaN  205 grams  
4                  NaN  Miljan David Tanic    NaN NaN  205 grams  

[5 rows x 27 columns]

In [3]:
df.columns

Index(['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded',
       'dateUpdated', 'dimension', 'ean', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'prices', 'reviews.date',
       'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating',
       'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username', 'sizes',
       'upc', 'weight'],
      dtype='object')

In [4]:
df['id'].unique()

array(['AVpe7AsMilAPnD_xQ78G', 'AVpfBEWcilAPnD_xTGb7',
       'AVpff7_VilAPnD_xc1E_', 'AV00lzP7GV-KLJ3ac0uk',
       'AV1T0_7M-jtxr-f31CoX', 'AVpfpzCi1cnluZ0-oxEr',
       'AV00l7jV-jtxr-f30lnX', 'AV1T09XZ-jtxr-f31CoT',
       'AV3as-VX-jtxr-f3_PPu', 'AV00lzd5GV-KLJ3ac0ul',
       'AV1T1nWrglJLPUi8H8Yz', 'AV1T09fyvKc47QAVgf2R',
       'AV1T0-J7vKc47QAVgf2T', 'AV1T0_ti-jtxr-f31CoV',
       'AVph5AshLJeJML43f_fT', 'AV1T0_tnvKc47QAVgf2V',
       'AV1T19jBvKc47QAVgf3S', 'AVpg4dIu1cnluZ0-7fWM',
       'AV2Mus6LGV-KLJ3alnyc', 'AV3atCk2glJLPUi8SQna',
       'AVphEeRyilAPnD_x035P', 'AV29VS9cvKc47QAVp03c',
       'AV000tWuGV-KLJ3ac2-b', 'AV1T1nR5-jtxr-f31CpL',
       'AV1T19k3GV-KLJ3adSMS', 'AV1T19lYglJLPUi8H8Y_',
       'AV29ePzlGV-KLJ3amjUT', 'AV1T19jOglJLPUi8H8Y9',
       'AV1T19mDGV-KLJ3adSMT', 'AV1T1u7jvKc47QAVgf3J',
       'AV1T19kvglJLPUi8H8Y-', 'AV1Nik13-jtxr-f31AFO',
       'AVpfldWhLJeJML43_7zF', 'AV1T1nJ_GV-KLJ3adSMC',
       'AVpfLiCSilAPnD_xWpk_', 'AVsRjfwAU2_QcyX9PHqe',
       'AV

In [5]:
df['asins'].unique()

array(['B00QJDU3KY', 'B002Y27P3M', 'B00DU15MU4', 'B01LW1MS9C',
       'B01FWSVGQQ', 'B00DOPNLJ0', 'B00NO8LX7E', 'B00LWHUAF0',
       'B00KDRQEYQ', 'B00OQVZDJM', 'B00QJDVBFU', 'B00VKLBU3Y',
       'B010BWYP20', 'B00VKM5NFY', 'B01KIOU4EO', 'B0117U8JSG',
       'B01A08ECQY', 'B01J2G4VBG', 'B00QJDS7I4', 'B00U879XZ8',
       'B010EK1GOE', 'B00LWHUB9A', 'B00ZS0G0PG', 'B01A08E70K',
       'B00PD81ETU', 'B06XDD27LJ', 'B00CX5P8FC', 'B07194GPJV',
       'B008GG93YE,B00LWHUBPO,B0051QYGXA', 'B071NMTDHR', 'B0117U82EM',
       'B0711C7WL2', 'B01M3ULMWP', 'B00LWHU9D8', 'B0716JZKLT',
       'B01BRWH8G8', 'B01M4NRFXX', 'B01KVZDFD2', 'B01M4NU4OM',
       'B008GGCAVM,B00DOPNMVM', 'B00KSR13CE', 'B01M71HRMY', 'B01K8B8YA8',
       'B010BWYDYA', 'B01KIOU214', 'B00DOPNK14',
       'B00DOPNO4M,B00BWYQ9YE,B00CYQPMJC,B00CUU1CGY,B00BWYRF7E,B00CYQP3AK',
       'B01BH83OOM', 'B00K5W9WZW', 'B01E9AHU8Q', 'B01HC1S9HU',
       'B00HX0SRXW', 'B00LORGAG6', 'B00NO8JJZW'], dtype=object)

In [6]:
df['brand'].unique()

array(['Amazon', 'Moshi'], dtype=object)

In [7]:
df['categories'].unique()

array(['Amazon Devices,mazon.co.uk',
       'Kindle Store,Amazon Devices,Electronics',
       'Categories,Amazon Devices,Streaming Media Players',
       'Amazon Devices',
       'Categories,Amazon Devices,Electronics Features,Streaming Media Players,Consumer Electronics,See more Amazon Fire TV Digital HD Media Streamer (Late...',
       'Amazon Devices & Accessories,Amazon Device Accessories,Power Adapters & Cables,Kindle Store,Kindle E-Reader Accessories,Kindle Paperwhite Accessories',
       'Amazon Devices,Kindle Store', 'Electronics,Amazon Devices',
       'Amazon Devices,Kindle Accessories',
       'Amazon Devices,Electronics,Kindle Store',
       'Amazon Devices,Electronics,Kindle Store,Amazon Echo',
       'Amazon Devices,Kindle Store,Kindle Accessories',
       'Amazon Devices,Kindle Store,buy a kindle',
       'Amazon Devices,Home,Smart Home & Connected Living,Smart Hubs & Wireless Routers,Smart Hubs,Home Improvement,Home Safety & Security,Alarms & Sensors,Home Security,Amazo

In [8]:
df['colors'].unique()

array([nan, 'GB', 'Black', 'Clear'], dtype=object)

In [9]:
df['dateAdded'].unique()

array(['2016-03-08T20:21:53Z', '2015-01-17T12:14:51Z',
       '2016-02-03T04:11:33Z', '2017-07-12T02:18:30Z',
       '2017-07-18T03:53:08Z', '2015-06-02T08:44:19Z',
       '2017-07-12T02:19:04Z', '2017-07-18T03:52:58Z',
       '2017-08-13T08:26:49Z', '2017-07-12T02:18:31Z',
       '2017-07-18T03:55:50Z', '2017-07-18T03:53:01Z',
       '2017-07-18T03:53:07Z', '2016-02-07T20:58:01Z',
       '2017-07-18T03:57:20Z', '2016-02-07T21:16:28Z',
       '2017-07-29T05:03:59Z', '2017-08-13T08:27:06Z',
       '2015-11-06T01:15:13Z', '2017-08-07T15:34:22Z',
       '2017-07-12T03:23:38Z', '2017-07-18T03:55:49Z',
       '2017-07-18T03:57:21Z', '2017-08-07T16:13:29Z',
       '2017-07-18T03:56:21Z', '2017-07-16T22:34:55Z',
       '2016-02-07T20:58:00Z', '2015-05-22T18:12:20Z',
       '2017-03-27T20:56:09Z', '2017-06-22T20:55:23Z',
       '2015-06-01T14:11:59Z', '2017-06-22T20:48:36Z',
       '2017-06-22T20:55:24Z', '2016-05-20T11:07:30Z',
       '2017-02-28T00:19:16Z', '2015-06-02T08:45:09Z',
       '20

In [10]:
df['dateUpdated'].unique()

array(['2017-07-18T23:52:58Z', '2015-11-01T00:05:54Z',
       '2017-08-08T22:03:27Z', '2017-08-13T08:28:52Z',
       '2017-08-13T08:28:51Z', '2017-08-07T15:41:59Z',
       '2017-08-13T08:29:10Z', '2017-08-13T08:29:03Z',
       '2017-08-13T08:28:41Z', '2017-07-18T23:46:14Z',
       '2017-08-10T20:14:43Z', '2017-08-13T08:28:47Z',
       '2017-08-13T08:28:54Z', '2017-08-13T08:29:02Z',
       '2017-07-29T02:16:34Z', '2017-08-13T08:29:04Z',
       '2017-08-07T15:06:25Z', '2017-08-13T08:29:09Z',
       '2017-07-18T23:52:40Z', '2017-08-10T20:25:53Z',
       '2017-07-25T02:04:06Z', '2017-08-11T03:11:21Z',
       '2017-08-11T03:14:37Z', '2017-07-18T23:52:39Z',
       '2017-08-08T22:03:26Z', '2017-08-13T08:28:46Z',
       '2017-07-31T05:12:13Z', '2017-08-13T08:28:53Z',
       '2017-07-25T17:43:00Z', '2017-07-25T17:42:44Z',
       '2017-07-25T17:42:39Z', '2017-08-13T08:29:12Z',
       '2017-07-25T17:42:56Z', '2017-07-25T17:42:46Z',
       '2017-08-13T08:28:13Z', '2017-08-13T08:31:08Z',
       '20

In [11]:
df['dimension'].unique()

array(['169 mm x 117 mm x 9.1 mm', nan, '4.8 in x 6.6 in x 3.2 in'],
      dtype=object)

In [12]:
df['ean'].unique()

array([        nan, 8.48719e+11, 8.41667e+11])

In [13]:
df['keys'].unique()

array(['kindlepaperwhite/b00qjdu3ky',
       'kindlekeyboard/b002y27p3m,amazon/d01101',
       '848719035551,0848719035551,certifiedrefurbishedamazonfiretvpreviousgeneration1st/b00du15mu4',
       'amazonechodotcasefitsechodot2ndgenerationonlyindigofabric/b01lw1ms9c',
       'amazontapslingcovertangerine/b01fwsvgqq',
       'kindlefirehdx89/b00dopnlj0',
       'amazonechodotcasefitsechodot2ndgenerationonlysaddletanleather/b01lw1ms9c',
       'amazontapslingcoverblue/b01fwsvgqq',
       'amazonechodotcasefitsechodot2ndgenerationonlysandstonefabric/b01lw1ms9c',
       'allnewamazonfiretvgamecontroller/b00no8lx7e',
       'firehd7tablet/b00lwhuaf0',
       'amazonfiretvgamecontroller/b00no8lx7e',
       'amazontapslingcoverwhite/b01fwsvgqq',
       'amazontapslingcovermagenta/b01fwsvgqq',
       'certifiedrefurbishedkindleereader/b00kdrqeyq',
       'amazontapslingcovergreen/b01fwsvgqq',
       'kindlepaperwhiteereaderblack/b00oqvzdjm',
       'kindlepaperwhite3g/b00qjdvbfu',
       'fire

In [14]:
df['manufacturer'].unique()

array(['Amazon', nan, 'AMDSI'], dtype=object)

In [15]:
df['manufacturerNumber'].unique()

array([nan, 'D01101', '8.48719E+11', 'B01BH83OOM', 'KA416Y', 'CV98LM',
       'DR49WK'], dtype=object)

In [16]:
df['name'].unique()

array(['Kindle Paperwhite', 'Kindle Keyboard',
       'Certified Refurbished Amazon Fire TV (Previous Generation - 1st)',
       'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Indigo Fabric',
       'Amazon Tap Sling Cover - Tangerine', 'Kindle Fire HDX 8.9"',
       'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Saddle Tan Leather',
       'Amazon Tap Sling Cover - Blue',
       'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Sandstone Fabric',
       'All-New Amazon Fire TV Game Controller', 'Fire HD 7 Tablet',
       'Amazon Fire TV Game Controller', 'Amazon Tap Sling Cover - White',
       'Amazon Tap Sling Cover - Magenta',
       'Certified Refurbished Kindle E-reader',
       'Amazon Tap Sling Cover - Green',
       'Kindle Paperwhite E-reader - Black', 'Kindle Paperwhite 3G',
       'Fire HD 10 Tablet with Alexa',
       'Amazon Echo Dot Case (fits Echo Dot 2nd Generation only) - Merlot Leather',
       'Fire Kids Edition Tablet', 'Echo Sho

In [17]:
df['prices'].unique()

array(['[{"amountMax":139.99,"amountMin":139.99,"currency":"USD","dateAdded":"2017-07-18T23:52:58Z","dateSeen":["2017-07-15T18:10:23.807Z","2016-03-16T00:00:00Z"],"isSale":"false","merchant":"Amazon.com","shipping":"FREE Shipping.","sourceURLs":["https://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built/dp/B00QJDU3KY/ref=lp_6669702011_1_7/132-1677641-8459202?s=amazon-devices&ie=UTF8&qid=1498832761&sr=1-7","http://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built-/dp/B00QJDU3KY"]},{"amountMax":119.99,"amountMin":119.99,"condition":"new","currency":"EUR","dateAdded":"2016-03-08T20:21:53Z","dateSeen":["2016-01-29T00:00:00Z"],"isSale":"false","merchant":"Amazon EU Sarl","shipping":"free","sourceURLs":["http://www.amazon.co.uk/Kindle-Paperwhite-Resolution-Display-Built-/dp/B00QJDU3KY"]},{"amountMax":139.99,"amountMin":139.99,"condition":"new","currency":"CAD","dateAdded":"2016-03-08T20:21:53Z","dateSeen":["2016-01-11T00:00:00Z"],"isSale":"false","merchant":"Amazon"

In [18]:
df['reviews.date'].unique()

array(['2015-08-08T00:00:00.000Z', '2015-09-01T00:00:00.000Z',
       '2015-07-20T00:00:00.000Z', '2017-06-16T00:00:00.000Z',
       '2016-08-11T00:00:00.000Z', '2015-07-08T00:00:00Z',
       '2015-09-01T00:00:00Z', '2015-07-03T00:00:00Z',
       '2015-08-08T00:00:00Z', '2015-07-20T00:00:00Z',
       '2015-07-01T00:00:00Z', '2015-08-05T00:00:00Z', nan,
       '2014-05-05T05:00:00Z', '2014-05-03T05:00:00Z',
       '2014-05-04T05:00:00Z', '2010-09-02T05:00:00Z',
       '2014-05-02T05:00:00Z', '2014-05-06T05:00:00Z',
       '2014-05-07T05:00:00Z', '2014-04-03T00:00:00Z',
       '2014-04-07T00:00:00Z', '2014-04-06T00:00:00Z',
       '2017-01-30T00:00:00.000Z', '2016-11-06T00:00:00.000Z',
       '2016-11-11T00:00:00.000Z', '2016-11-28T00:00:00.000Z',
       '2016-11-17T00:00:00.000Z', '2017-04-20T00:00:00.000Z',
       '2017-01-12T00:00:00.000Z', '2017-01-11T00:00:00.000Z',
       '2016-04-01T00:00:00.000Z', '2016-12-15T00:00:00.000Z',
       '2013-11-07T00:00:00.000Z', '2015-03-15T00:00:00

In [19]:
df['reviews.sourceURLs'].unique()

array(['https://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built/dp/B00QJDU3KY/ref=lp_6669702011_1_7/132-1677641-8459202?s=amazon-devices&ie=UTF8&qid=1498832761&sr=1-7',
       'http://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built-/dp/B00QJDU3KY',
       'http://www.amazon.ca/product-reviews/B00QJDU3KY',
       'http://www.amazon.com/Kindle-Wireless-Reader-Wifi-Graphite/dp/B002Y27P3M',
       'http://www.amazon.com/Kindle-Wireless-Reader-Wifi-Graphite/product-reviews/B002Y27P3M/ref=cm_cr_dp_see_all_btm?ie=UTF8&showViewpoints=1&sortBy=bySubmissionDateDescending',
       'https://www.amazon.com/Kindle-Wireless-Reader-Wifi-Graphite/dp/B002Y27P3M',
       'http://www.amazon.com/Certified-Refurbished-Amazon-Fire-TV/dp/B00DU15MU4',
       'http://www.amazon.com/Certified-Refurbished-Amazon-Previous-Generation/dp/B00DU15MU4',
       'https://www.amazon.com/Amazon-Echo-Case-fits-Generation/dp/B01K9KWA3U/ref=sr_1_18/144-2524480-1433355?s=fiona-hardware&ie=UTF8&qid

In [20]:
df['reviews.numHelpful'].unique()

array([139., 126.,  69.,   2.,  17.,  nan, 303., 138., 207., 245.,  43.,
        14.,   5.,  30.,  68., 123., 122.,  36., 402., 330.,  85.,  59.,
       694.,  38.,  15.,  22.,   4., 719., 641., 498., 716., 739.,  48.,
         8.,  24.,   3.,  19.,  13., 671., 936., 206., 586., 120., 160.,
        25., 769., 357., 656.,  50., 669., 194., 350., 848., 294., 729.,
        56.,   6.,  64.,  34.,  83.,  29.,  27., 143.,  16.,  18.,  31.,
        61.,  82., 581., 870., 177., 215.,  88., 599., 221., 750., 790.,
       102., 323., 834.,  74.,  11., 346.,  89., 111., 190., 172.,   7.,
         9.,  35.,  63., 449., 620., 142.,  87.,  12.,  40., 281., 216.,
       822., 185., 944., 551., 182., 685., 432., 975.,  20., 745., 236.,
       407., 287., 249., 170., 112., 201.,  37.,  41.,  21.,  66., 147.,
       125., 403., 517.,   0., 180., 228., 997., 505., 965., 443., 358.,
       510., 326., 151., 890., 754., 902., 512.,  75., 205., 456., 932.,
       771., 459.,  52., 781., 966., 539., 704.,  7

In [21]:
df['reviews.rating'].unique()

array([ 5.,  4., nan,  3.,  1.,  2.])

In [22]:
df['reviews.doRecommend'].unique()

array([nan, True, False], dtype=object)

In [23]:
df['reviews.text'].unique()

array(["I initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing: the paperwhite is great, but if you have spending money, go for the voyage.Fortunately, I had friends who owned each, so I ended up buying the paperwhite on this basis: both models now have 300 ppi, so the 80 dollar jump turns out pricey the voyage's page press isn't always sensitive, and if you are fine with a specific setting, you don't need auto light adjustment).It's been a week and I am loving my paperwhite, no regrets! The touch screen is receptive and easy to use, and I keep the light at a specific setting regardless of the time of day. (In any case, it's not hard to change the setting either, as you'll only be changing the light level at a certain time of day, not every now and then while reading).Also glad that I went for the international shipping option with Amazon. Extra expense, but delivery was on time, with tracking, and I didnt need to worry a

In [24]:
df['reviews.title'].unique()

array(['Paperwhite voyage, no regrets!',
       'One Simply Could Not Ask For More',
       'Great for those that just want an e-reader', ...,
       'replacing an even worse remote. Waste of time', 'Overpriced',
       'I am sending all of this crap back to amazon and canceling this Fire subscription'],
      dtype=object)

In [25]:
df['reviews.userCity'].unique()

array([nan])

In [26]:
df['reviews.userProvince'].unique()
                                

array([nan])

In [27]:
df['reviews.username'].unique()

array(['Cristina M', 'Ricky', 'Tedd Gardiner', 'Dougal',
       'Miljan David Tanic', 'Kelvin Law', 'Bandler', 'Miguel Martinez',
       'Magnus Brattemark', 'Janet Matthews Jan', "John Kat's the brains",
       'samira', 'Louis simard', 'JanetC', 'Shepherd', 'Brenda',
       'Fil Gambatesa', 'Roy Bennett', 'satisfied customer',
       'Jeffrey Stanley', 'Matthew Coenen', 'Ron Cronovich', 'C. Tipton',
       'D. Tatro', 'M. Lansford Kindle fave', 'Jean F. Bryant Wordwright',
       'Jeff Maddox', 'Mr Goodwrench', 'ken', 'Lucky Luke', 'George',
       'Kelly Beaumont', 'Alexandr Petak', 'Di', 'Gregory P. Baker',
       'Mandy', 'Dallas', 'William Hardin', 'D. Miyao', 'dm',
       'Corey Clarke', 'A.C', 'Vincent Pompei', 'Bob', 'JB 85',
       'C. Morrow', 'Ryan', 'Jbird', 'Devin Stephens',
       'CHRISTOPHER JONES', 'B. Tarbuck', 'Amazon Reviewer',
       'Samuel Ruiz', 'Tina L. Harmon', 'Amazon Customer',
       'Things I Love Like,', 'Kimberly R. Norton', 'Randall M.',
       'Dean S

In [28]:
df['sizes'].unique()

array([nan])

In [29]:
df['upc'].unique()

array([        nan, 8.48719e+11, 8.41667e+11])

In [30]:
df['weight'].unique()

array(['205 grams', '1.1 pounds', nan, '1.6 ounces', '1.75 lbs',
       '0.8 ounces', '4 ounces', '5 ounces', '4.6 ounces', '2.4 ounces'],
      dtype=object)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1597 entries, 0 to 1596
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id                    1597 non-null   object 
 1   asins                 1597 non-null   object 
 2   brand                 1597 non-null   object 
 3   categories            1597 non-null   object 
 4   colors                774 non-null    object 
 5   dateAdded             1597 non-null   object 
 6   dateUpdated           1597 non-null   object 
 7   dimension             565 non-null    object 
 8   ean                   898 non-null    float64
 9   keys                  1597 non-null   object 
 10  manufacturer          965 non-null    object 
 11  manufacturerNumber    902 non-null    object 
 12  name                  1597 non-null   object 
 13  prices                1597 non-null   object 
 14  reviews.date          1217 non-null   object 
 15  reviews.doRecommend  

In [32]:
df.isnull().sum()

id                         0
asins                      0
brand                      0
categories                 0
colors                   823
dateAdded                  0
dateUpdated                0
dimension               1032
ean                      699
keys                       0
manufacturer             632
manufacturerNumber       695
name                       0
prices                     0
reviews.date             380
reviews.doRecommend     1058
reviews.numHelpful       697
reviews.rating           420
reviews.sourceURLs         0
reviews.text               0
reviews.title             17
reviews.userCity        1597
reviews.userProvince    1597
reviews.username          17
sizes                   1597
upc                      699
weight                   911
dtype: int64

In [33]:
df.shape

(1597, 27)

In [34]:
df = df[['reviews.text']]

In [35]:
df

reviews.text
0     I initially had trouble deciding between the p...
1     Allow me to preface this with a little history...
2     I am enjoying it so far. Great for reading. Ha...
3     I bought one of the first Paperwhites and have...
4     I have to say upfront - I don't like coroporat...
...                                                 ...
1592  This is not the same remote that I got for my ...
1593  I have had to change the batteries in this rem...
1594  Remote did not activate, nor did it connect to...
1595  It does the job but is super over priced. I fe...
1596  I ordered this item to replace the one that no...

[1597 rows x 1 columns]

# Text Preprocessing

Remove Punctuations
Remove stopwords
Remove Lemmatization

In [36]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()

In [53]:

stop_words = set(stopwords.words('english'))
print(stop_words)

{'if', "you've", 'its', 'have', "won't", 'at', "you're", 'themselves', "isn't", 't', 'hadn', 'them', 'been', "shan't", 'about', 'other', 'doing', 'why', 'once', 'too', 'our', 'm', 'up', 'out', 'such', 'each', 'with', 'i', 'between', 'in', 'the', 'yourself', 'being', 'had', "haven't", 'during', 'from', 'after', 'we', 'on', "should've", 'what', 'then', 'there', "you'd", 'how', "doesn't", 'do', 'his', 'to', "that'll", 'isn', 'him', 'didn', 'who', 'any', 'wasn', 'further', 'having', 'ain', 'some', 'll', "hasn't", 'ma', 'couldn', 'itself', "didn't", "wouldn't", 'than', 'this', 'but', 'so', 'which', "don't", 'shan', 'is', "mustn't", "she's", 'when', 'd', 'you', "wasn't", 'before', "mightn't", 'where', 'most', 'your', 'are', 'won', 'into', 'as', 'again', 'while', 'needn', 'am', 'here', 're', 'above', 'off', 'an', 'they', 'will', 'own', 'don', "weren't", 'has', 'same', 'me', 'himself', 'did', 'yours', 've', 'her', 'weren', 'aren', 'were', 'can', 'for', 'their', "hadn't", 'mustn', 's', 'doesn',

In [37]:
corpus = []
for i in range(len(df)):
    rp=re.sub('[^a-zA-Z]',' ',df['reviews.text'][i])
    rp = rp.lower()
    rp = rp.split()
    rp = [wnl.lemmatize(word) for word in rp if not word in set(stopwords.words('english'))]

    rp = ' '.join(rp)
    corpus.append(rp)
    
print(corpus)    
   

['initially trouble deciding paperwhite voyage review le said thing paperwhite great spending money go voyage fortunately friend owned ended buying paperwhite basis model ppi dollar jump turn pricey voyage page press always sensitive fine specific setting need auto light adjustment week loving paperwhite regret touch screen receptive easy use keep light specific setting regardless time day case hard change setting either changing light level certain time day every reading also glad went international shipping option amazon extra expense delivery time tracking didnt need worry custom may used third party shipping service', 'allow preface little history casual reader owned nook simple touch read harry potter series girl dragon tattoo series brave new world key title fair say nook get much use many others may gotten fast forward today full week new kindle paperwhite admit love kindle reading let relate review love reading back kindle investment experience receive buy kindle simply paying 

# Vectorization

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

X = cv.fit_transform(corpus)

# Modelling using LDA

In [46]:
from sklearn.decomposition import LatentDirichletAllocation
model = LatentDirichletAllocation()
model.fit(X)

LatentDirichletAllocation()

In [47]:
topic_results = model.transform(X)

In [61]:
topic_results[0]

array([0.00108727, 0.59424936, 0.00108748, 0.00108717, 0.2662265 ,
       0.00108718, 0.00108718, 0.13191357, 0.00108707, 0.00108722])

In [62]:
topic_results[0].argmax()

1

# Combining with Original Data

In [65]:
df['group'] = [topic_results.argmax(axis=1)for topic in topic_results]

In [66]:
df.head()

reviews.text  \
0  I initially had trouble deciding between the p...   
1  Allow me to preface this with a little history...   
2  I am enjoying it so far. Great for reading. Ha...   
3  I bought one of the first Paperwhites and have...   
4  I have to say upfront - I don't like coroporat...   

                                               group  
0  [1, 1, 5, 1, 1, 1, 1, 1, 1, 5, 1, 1, 5, 1, 1, ...  
1  [1, 1, 5, 1, 1, 1, 1, 1, 1, 5, 1, 1, 5, 1, 1, ...  
2  [1, 1, 5, 1, 1, 1, 1, 1, 1, 5, 1, 1, 5, 1, 1, ...  
3  [1, 1, 5, 1, 1, 1, 1, 1, 1, 5, 1, 1, 5, 1, 1, ...  
4  [1, 1, 5, 1, 1, 1, 1, 1, 1, 5, 1, 1, 5, 1, 1, ...

# showing Top words per Topic

In [59]:
for index, topic in enumerate(model.components_):
    print(f'The Top 10 WORDS For Topic #{index}')
    feature_names = list(cv.vocabulary_.keys())
    top_words_indices = topic.argsort()[-10:]
    top_words = [feature_names[i] for i in top_words_indices]
    print(top_words)
    print('\n')


The Top 10 WORDS For Topic #0
['awesome', 'escape', 'fellow', 'editgid', 'activate', 'blink', 'practice', 'testify', 'excessive', 'paperwhites']


The Top 10 WORDS For Topic #1
['corporate', 'workremote', 'reliving', 'disappointment', 'reporting', 'temporary', 'fly', 'reflect', 'ray', 'dearly']


The Top 10 WORDS For Topic #2
['instantly', 'ganes', 'fact', 'preventing', 'gamestbd', 'paperwhites', 'providing', 'practice', 'reflect', 'trivia']


The Top 10 WORDS For Topic #3
['costing', 'briefly', 'residue', 'fly', 'mentioning', 'researching', 'paperwhites', 'reporting', 'providing', 'face']


The Top 10 WORDS For Topic #4
['fly', 'editgid', 'escape', 'receiving', 'providing', 'filtered', 'briefly', 'residue', 'gorilla', 'displaying']


The Top 10 WORDS For Topic #5
['riptide', 'knowledge', 'reporting', 'carefully', 'dearly', 'workremote', 'reliving', 'sporadicno', 'calendar', 'face']


The Top 10 WORDS For Topic #6
['depend', 'conditioning', 'paperwhites', 'escape', 'noticed', 'editgid'